services:
  - type: web
    name: uiet-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    pythonVersion: 3.8  # ✅ CORRECT placement — not nested in 'build'
    envVars:
      - key: RASA_API_URL
        value: http://localhost:5005/webhooks/rest/webhook
