services:
  - type: web
    name: uiet-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: RASA_API_URL
        value: http://localhost:5005/webhooks/rest/webhook
